### PR TITLE
Add phpstan for static analysis and fixes - WIP

### PR DESCRIPTION
**Pull request by mavimo**
SSIA

### CODE REVIEW

**Comment by mavimo** [comment]
@techoner I'm try to introduce static analysis in order to prevent issues on codebase, let me know if you have some doubt on this approach, thx!

**Comment by techoner** [comment]
lgtm.

**Comment by techoner** [comment]
lgtm.

**Comment by mavimo** [comment]
@techoner I'm sorry but the current version do not fix all phpstan issues, there are errors in CI :(

**Pull request merged**
