### PR TITLE
Fix the bug that getImplicitUsersForPermission() cannot get users in role, similar to Go issue #443

### PR DESCRIPTION
**Pull request by zhhzone**
Fix: https://github.com/php-casbin/php-casbin/issues/65

### CODE REVIEW

**Comment by hsluoyz** [comment]
@zhhzone commits are not good:

image

**Comment by techoner** [comment]
@zhhzone Then add some test code, merge into one commit.

**Comment by zhhzone** [comment]
ok.  I will do it

**Comment by hsluoyz** [comment]
@zhhzone can you squash your 4 commits into one?

@techoner plz review.

**Pull request closed without merging**
